### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by thco** [decipherinc/angular-tipped#19]
In the doc, you say "use fv.tipped" module but the correct name seems to be "decipher.tipped"

EDIT : on Github, the module name is "fv.tipped", my bad, maybe a branch problem ?
EDIT 2 : Ok, I don't know why bower gives me the v0.3.0 version... Updated to v1.0.0-1.

**Comment by boneskull** [comment]
@thco v1.0.0-1 is an release candidate for 1.0.0 until we can update the documentation with new features and behavior.  Feel free to use it though, and let me know if you find issues.  see #17
